### ISSUE TITLE
Version tags missing on repository (dependencies locked to ^7.1)

### ISSUE THREAD

**Issue by xewl** [shipcore-nl/dhlparcel-api-php#4]
Currently this is the most complete implementation available for this API, however..

Installing this, currently fails on 5.5.9 due to dependent packages:
![image](https://user-images.githubusercontent.com/245041/53806422-3e31e600-3f4d-11e9-91e4-c4bc5ac08b71.png)

Probably because there's only "dev-master"? (no tags, like 0.x)

(Yes, I know, I should be on 7.1+ `¯\_(ツ)_/¯`)

**Comment by extroniks** [comment]
It fails because the shipcore-nl/data-object package depends on doctrine/annotations of at least v1.4.0 which states this as it's needed PHP versions:
"php": "^5.6 || ^7.0"

So it seems indeed the package is not 5.5.X compatible.
First version of doctrine/annotations to allow PHP 5.5.X is v1.2.7 which was not tested with this package.

Easiest solution would be using PHP 5.6 or higher if possible with your other dependencies (I know it might not be optimal though if you have legacy code on your hands).

**Comment by xewl** [comment]
I solved the problem on my side, by going back to "legacy-mode" and doing the isAccessible & isRequired checks directly on the Property object itself, thus not using or loading these dependencies. The version update on our side will be done when the time is right :)
